spring:
#  profiles:
#    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/querydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true # hibernate ? ???? ???? system.out ?? ??
        format_sql: true
        use_sql_comments: true # 실행되는 jpql 보는 옵션


logging.level:
  org.hibernate.SQL: debug # hibernate ? ???? ???? logger ? ??? ??.
# org.hibernate.type: trace # bind parameter ?? ? ??? ? ??